### PR TITLE
Use `critical_section` crate.

### PR DESCRIPTION
**Pull request by reitermarkus**
Switch to using `critical_section` crate.

### CODE REVIEW

**Comment by katyo** [comment]
Actual versions of `riscv` crate isn't compatible with this crate, bacause `&mut CriticalSection` argument was removed from closure.
This PR solves it by removing potentially incompatible dependencies (`cortex-m`, `riscv` crates).

**Comment by Disasm** [comment]
Hi! Could you rebase your PR and add a changelog entry?

**Comment by reitermarkus** [comment]
@Disasm, PR is rebased.

**Comment by reitermarkus** [comment]
@Disasm, I fixed the CI matrix.

**Review by Disasm — APPROVED** [review]
Thank you!

**Pull request merged**
