### PR TITLE
Updating driver to usb-device 0.3.0

### PR DESCRIPTION
**Pull request by ryan-summers**
This PR bumps the `usb-device` version used to 0.3.0, which I just released earlier today. I've tested these changes on Stabilizer with a USB-CDC-ACM port and verified things work as expected.

Most of the changes are from rustfmt here.

### CODE REVIEW

**Comment by Disasm** [comment]
Thanks! I merged a PR which enforces rustfmt checks: https://github.com/stm32-rs/synopsys-usb-otg/pull/40
Could you rebase your PR to make the diff simpler?

**Comment by ryan-summers** [comment]
Should be much smaller now, thanks for the rustfmt checks! :)

**Comment by ryan-summers** [comment]
Ping back over to @disasm - if you don't have time, I'll merge and release later today/this week, so no worries. Thanks for helping!

**Comment by Disasm** [comment]
Hi! I started testing the proposed changes to the driver with the [variety of boards](https://github.com/Disasm/usb-otg-workspace/) I have. The test plan is quite big and it also includes https://github.com/stm32-rs/synopsys-usb-otg/pull/25 which I wanted to integrate before the 0.3.0 release. So far testing is complete by ~25%. If you think that the release should be prioritized, then I can prioritize testing of this update, but otherwise my plan is to finish testing on weekend this or next week.

**Comment by ryan-summers** [comment]
Hmm, personally I'd be more inclined to release early and often, and we can add in that support once its fully tested. It won't change any of the API, so it would be simple enough to include that in a patch release. What are your thoughts on that?

**Comment by Disasm** [comment]
That's what I want to make sure: that usb-device 0.3.0 is fully tested together with this driver :) Ok, I will test this update next, then let's make a new release of `synopsys-usb-otg` and then I'll proceed with other updates.

**Comment by Disasm** [comment]
Test results:
* now one of the test_class tests fails because synchronous endpoints are not implemented
* serial test fails with timeout for HighSpeed devices (not sure yet what is the reason, may be a regression in usbd-serial)
* compliance tests fail (tests 9.4, 9.9, 9.21) - all these tests failed before the update
* enumeration fails with FS peripheral on STM32F723 (https://github.com/stm32-rs/synopsys-usb-otg/issues/24)

**Comment by Disasm** [comment]
I found that serial test behavior depends on the USB port type used: test passes if USB 2.0 port is used, fails if USB 3.0 port is used. And this is also a bug which was present in older versions of `synopsys-usb-otg`.

**Review by Disasm — APPROVED** [review]

**Pull request merged**
