### PR TITLE
Remove reset values since they are not used in this crate.

### PR DESCRIPTION
**Pull request by engstad**

### CODE REVIEW

**Comment by Disasm** [comment]
This code is auto-generated, I'm not sure it's a good idea to modify it.

**Comment by engstad** [comment]
> This code is auto-generated, I'm not sure it's a good idea to modify it.

Is it? Who generates it?

**Comment by Disasm** [comment]
https://github.com/adamgreig/stm32ral

**Comment by engstad** [comment]
> https://github.com/adamgreig/stm32ral

Ah, it must be done manually then, since we don't depend on the crate and we don't have any scripts running it.

**Comment by Disasm** [comment]
Yes, there is no need to regenerate it each build as this code doesn't change often.

**Comment by adamgreig** [comment]
It's probably fair to say it's vendored here, I doubt it would ever need to be updated from stm32ral itself so you could safely remove the reset values now and always add them back if you started to need them. That said, I doubt it buys you much in compile time and shouldn't impact code size at all?

**Comment by Disasm** [comment]
Nope, I have plans updating it! Original SVD lacks a few fields, but I need to upstream these to stm32-rs first.

**Pull request closed without merging**
